"""Repository rule exposing a preinstalled system library as a `cc_library`.

Intended for platforms where some dependencies are only reasonably available
as OS packages (e.g. the `epoll-shim` and `libinotify` compatibility libraries
on OpenBSD). If the include directory is missing, the repository still loads
but its target is marked incompatible, so that `bazel query` keeps working on
platforms that do not use the library.
"""

_BUILD_TEMPLATE = """\
# Generated by //build_external/system_library:system_library.bzl
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = {name},
    hdrs = {hdrs},
    defines = select({{
        "@platforms//os:openbsd": {defines},
        "//conditions:default": [],
    }}),
    includes = {includes},
    linkopts = select({{
        "@platforms//os:openbsd": {linkopts},
        "//conditions:default": [],
    }}),
    target_compatible_with = {target_compatible_with},
)
"""

def _system_library_impl(rctx):
    name = getattr(rctx, "original_name", None)
    if not name:
        name = rctx.name.replace("~", "+").rsplit("+", 1)[-1]

    include_dir = rctx.path(rctx.attr.include_dir)
    if include_dir.exists:
        rctx.symlink(include_dir, "include")
        hdrs = 'glob(["include/**/*.h"])'
        includes = '["include"]'
        target_compatible_with = "[]"
    else:
        hdrs = "[]"
        includes = "[]"
        target_compatible_with = '["@platforms//:incompatible"]'

    rctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        name = repr(name),
        hdrs = hdrs,
        defines = repr(rctx.attr.defines),
        includes = includes,
        linkopts = repr(rctx.attr.linkopts),
        target_compatible_with = target_compatible_with,
    ))

system_library = repository_rule(
    implementation = _system_library_impl,
    attrs = {
        "defines": attr.string_list(
            doc = "Preprocessor defines propagated to every dependent target.",
        ),
        "include_dir": attr.string(
            doc = "Absolute path of the directory holding the library headers.",
            mandatory = True,
        ),
        "linkopts": attr.string_list(
            doc = "Linker flags needed to link against the library.",
        ),
    },
    doc = "Exposes a preinstalled system library as `@<name>//:<name>`.",
    local = True,
)
