system_library = use_repo_rule("@//build_external/system_library:system_library.bzl", "system_library")

# kqueue-based implementation of epoll(7), eventfd(2), signalfd(2) and
# timerfd(2) for the BSDs. On OpenBSD: `pkg_add epoll-shim`.
system_library(
    name = "epoll_shim",
    include_dir = "/usr/local/include/libepoll-shim",
    linkopts = [
        "-L/usr/local/lib",
        "-lepoll-shim",
    ],
)
